### ISSUE TITLE
Missing source files of png images

### ISSUE THREAD

**Issue by dietmarw** [OpenSimHub/OpenHPL#21]
PNG images should ideally be replaced by SVG images. That way we don't have to maintain 2 versions of the same image. 
- [ ] besad.png
- [x] darcyf.png
- [x] darcyf_zoomed.png
- [x] ghosts.png
- [x] kp.png
- [x] penstock.png
- [x] pipe.png
- [x] SharpOrificeSurgeTank.png
- [x] simplegen.png
- [x] surgepic.png
- [x] ThrottleValveSurgeTank.png
- [x] turbinepic.png

@pandeysudan27 could you see if you can get hold of pdfs that can be converted to SVGs or recreate them if not possible?

**Comment by pandeysudan27** [comment]
Ok. I will try to recreate these images then.

**Comment by dietmarw** [comment]
Some of them Bernt might have the sources for. So ask him too.

**Comment by pandeysudan27** [comment]
Remaining besad.png, turbinepic.png, simplegen.png, pipe.png, penstock.png  after merging from #23  .

I think we need to get the new notation for besad.png for homogenous notations.

**Comment by dietmarw** [comment]
Yes agreed.

**Comment by dietmarw** [comment]
All but the besad image were fixed in #23 .

**Comment by dietmarw** [comment]
I'm closing this as done without the update of the `besad.png` and track that rather in #38.
