### ISSUE TITLE
References to undefined connectors

### ISSUE THREAD

**Issue by maltelenz** [OpenSimHub/OpenHPL#44]
Here:

https://github.com/OpenSimHub/OpenHPL/blob/33085178e00e83cef034d76c8d5344b2c9b2d8f5/OpenHPL/Tests/HPElasticKPPenstockCompres.mo#L33

there are many references to undefined connectors:

```
Error: OpenHPL.Tests.HPElasticKPPenstockCompres [23:3-23:3] Unknown identifier reservoir.n.
Error: OpenHPL.Tests.HPElasticKPPenstockCompres [22:3-22:3] Unknown identifier intake.n.
Error: OpenHPL.Tests.HPElasticKPPenstockCompres [21:3-21:3] Unknown identifier surgeTank.n.
Error: OpenHPL.Tests.HPElasticKPPenstockCompres [20:3-20:3] Unknown identifier penstockKP.n.
Error: OpenHPL.Tests.HPElasticKPPenstockCompres [19:3-19:3] Unknown identifier turbine.n.
Error: OpenHPL.Tests.HPElasticKPPenstockCompres [18:3-18:3] Unknown identifier discharge.n.
Error: OpenHPL.Tests.HPElasticKPPenstockCompres [16:3-16:3] Unknown identifier aggregate.P_in.
Error: OpenHPL.Tests.HPElasticKPPenstockCompres [15:3-15:3] Unknown identifier aggregate.u.
```

Many other models in `OpenHPL.Tests` seem to have the same/similar issue.

**Comment by dietmarw** [comment]
The `Tests` package here contains a whole collection of intermediate tests done by the students during development. I did not yet have the time to sort through what was worthy of keeping and what was obsolete. They are not necessarily meant to pass.
